### ISSUE TITLE
sha512 result 

### ISSUE THREAD

**Issue by etam89** [secworks/sha512#2]
Hi, 

for the first test, SHA-512,
input is: single_block = 1024'h6162638000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018;
you expected output  is 
512'hDDAF35A193617ABACC417349AE20413112E6FA4E89A97EA20A9EEEE64B55D39A2192992A274FC1A836BA3C23A3FEEBBD454D4423643CE80E2A9AC94FA54CA49F

but when I use online sha512 hash generator, they show the output should be: 
5d79c10d0f3fb9c2566adf7d31903820dcedc1c10d0d395c6a637602d02b243c62d14276b6dc3266f7a2fd1bc353950970d471e74a971cea2db7b0d219228a7b

Did I get it wrong?

Thanks

**Comment by secworks** [comment]
You probably used a broken hash generator or did something wrong.

My implementation follows the NIST specification (see FIPS 180-2) and generates the expected result for the string "abc".
Also, if I check with the following online hash generator I get the same result:
https://www.browserling.com/tools/all-hashes

See the SHA-512 result in the middle column.
<img width="1258" alt="Screenshot 2021-04-07 at 08 16 31" src="https://user-images.githubusercontent.com/1833061/113819452-9e716280-9779-11eb-8951-4ba81d652ab4.png">
